# Generated by Django 3.0.7 on 2020-11-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outsourcing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('upload', models.FileField(upload_to='media/date/%Y/%M/%D/')),
                ('skills', models.CharField(max_length=100)),
                ('budget', models.CharField(choices=[('smallproject', 'smallproject'), ('mediumproject', 'mediumproject'), ('largeproject', 'largeproject')], max_length=100)),
                ('payment', models.CharField(choices=[('fixed', 'fixed'), ('hourly', 'hourly')], max_length=100)),
                ('bids', models.BooleanField(default=False)),
                ('time_reqd', models.CharField(max_length=100)),
            ],
        ),
    ]
